/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package algoviz;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import com.k33ptoo.components.KGradientPanel;
import com.k33ptoo.components.KButton;
import static java.awt.Color.black;
import static java.awt.Color.white;
import javax.swing.JLabel;
/**
 *
 * @author Lenovo
 */
public class searchLinear extends javax.swing.JFrame {

    /**
     * Creates new form searchLinear
     */
    public searchLinear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        btn4 = new com.k33ptoo.components.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        btn5 = new com.k33ptoo.components.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        btn6 = new com.k33ptoo.components.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        btn7 = new com.k33ptoo.components.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        btn8 = new com.k33ptoo.components.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        btn9 = new com.k33ptoo.components.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        btn1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        btn2 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        btn3 = new com.k33ptoo.components.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        reset = new com.k33ptoo.components.KButton();
        startSearch = new com.k33ptoo.components.KButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(900, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 204, 0));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(900, 800));
        kGradientPanel1.setLayout(null);

        btn4.setkStartColor(new java.awt.Color(0, 204, 51));
        btn4.setOpaque(false);
        btn4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        btn4.add(jLabel4);
        jLabel4.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn4);
        btn4.setBounds(60, 250, 120, 120);

        btn5.setkStartColor(new java.awt.Color(0, 204, 51));
        btn5.setOpaque(false);
        btn5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        btn5.add(jLabel5);
        jLabel5.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn5);
        btn5.setBounds(210, 250, 120, 120);

        btn6.setkStartColor(new java.awt.Color(0, 204, 51));
        btn6.setOpaque(false);
        btn6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        btn6.add(jLabel6);
        jLabel6.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn6);
        btn6.setBounds(360, 250, 120, 120);

        btn7.setkStartColor(new java.awt.Color(0, 204, 51));
        btn7.setOpaque(false);
        btn7.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        btn7.add(jLabel7);
        jLabel7.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn7);
        btn7.setBounds(60, 400, 120, 120);

        btn8.setkStartColor(new java.awt.Color(0, 204, 51));
        btn8.setOpaque(false);
        btn8.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        btn8.add(jLabel8);
        jLabel8.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn8);
        btn8.setBounds(210, 400, 120, 120);

        btn9.setkStartColor(new java.awt.Color(0, 204, 51));
        btn9.setOpaque(false);
        btn9.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        btn9.add(jLabel9);
        jLabel9.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn9);
        btn9.setBounds(360, 400, 120, 120);

        btn1.setkStartColor(new java.awt.Color(0, 204, 51));
        btn1.setOpaque(false);
        btn1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        btn1.add(jLabel1);
        jLabel1.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn1);
        btn1.setBounds(60, 100, 120, 120);

        btn2.setkStartColor(new java.awt.Color(0, 204, 51));
        btn2.setOpaque(false);
        btn2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        btn2.add(jLabel2);
        jLabel2.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn2);
        btn2.setBounds(210, 100, 120, 120);

        btn3.setkStartColor(new java.awt.Color(0, 204, 51));
        btn3.setOpaque(false);
        btn3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        btn3.add(jLabel3);
        jLabel3.setBounds(0, 0, 120, 120);

        kGradientPanel1.add(btn3);
        btn3.setBounds(360, 100, 120, 120);

        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetMouseExited(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        kGradientPanel1.add(reset);
        reset.setBounds(290, 570, 185, 45);

        startSearch.setText("Start");
        startSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startSearchMouseExited(evt);
            }
        });
        startSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSearchActionPerformed(evt);
            }
        });
        kGradientPanel1.add(startSearch);
        startSearch.setBounds(80, 570, 185, 45);

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3);
        jButton3.setBounds(0, 10, 10, 10);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 900, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents
KGradientPanel arBt[] = new KGradientPanel[9];
KGradientPanel bt[] = new KGradientPanel[9];
JLabel btL[] = new JLabel[9];
int btnWidth = 130;
int btnHeight = 140;
int btnNWidth = 120;
int btnNHeight = 120;
int elementFound = 0;
String fi;
String s1[] = new String[9];
int h;
boolean on = false;
    
    public Timer timerr = new Timer(900, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(h>=9){
                timerr.stop();
            }
            for(int g = 0;g<9;++g){
                arBt[g].setSize(btnNWidth,btnNHeight);
            }
           jButton3.doClick();
        }
    });
    
    public Timer blinktimerr = new Timer(500, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            btL[h].setForeground( on ? Color.black : Color.white);
            on = !on;
        }
    });
    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered
        reset.setSize(reset.getSize().width + 5, reset.getSize().height + 5);
    }//GEN-LAST:event_resetMouseEntered

    private void startSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startSearchMouseEntered
startSearch.setSize(startSearch.getSize().width + 5, startSearch.getSize().height + 5);
    }//GEN-LAST:event_startSearchMouseEntered

    private void resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseExited
reset.setSize(reset.getSize().width - 5, reset.getSize().height - 5);
    }//GEN-LAST:event_resetMouseExited

    private void startSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startSearchMouseExited
startSearch.setSize(startSearch.getSize().width - 5, startSearch.getSize().height - 5);
    }//GEN-LAST:event_startSearchMouseExited

    private void startSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSearchActionPerformed

if(elementFound == 1)
{
    JOptionPane.showMessageDialog(this,"Reset First!!");
}
else
{
bt[0] = btn1;
bt[1] = btn2;
bt[2] = btn3;
bt[3] = btn4;
bt[4] = btn5;
bt[5] = btn6;
bt[6] = btn7;
bt[7] = btn8;
bt[8] = btn9;
fi = JOptionPane.showInputDialog(null,"Enter Element to find:- ");
for(int u = 0; u<9; ++u){
    s1[u] = btL[u].getText();
}
        timerr.start();
}
    }//GEN-LAST:event_startSearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
arBt[0] = btn1;
arBt[1] = btn2;
arBt[2] = btn3;
arBt[3] = btn4;
arBt[4] = btn5;
arBt[5] = btn6;
arBt[6] = btn7;
arBt[7] = btn8;
arBt[8] = btn9;
btL[0] = jLabel1;
btL[1] = jLabel2;
btL[2] = jLabel3;
btL[3] = jLabel4;
btL[4] = jLabel5;
btL[5] = jLabel6;
btL[6] = jLabel7;
btL[7] = jLabel8;
btL[8] = jLabel9;
jButton3.setVisible(false);
setBtnSize(120,120);
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(h<9){
    if(s1[h].equals(fi)){
        timerr.stop();
        elementFound = 1;
        setBlack();
        blinktimerr.start();
        int temp = h+1;
        JOptionPane.showMessageDialog(this, "Found at "+ temp);
    }
    if(elementFound == 0){
        bt[h].setSize(btnWidth, btnHeight);
    ++h;
    }
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
blinktimerr.stop();
setBlack();
setWhite();
elementFound = 0;
h=0;

    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchLinear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchLinear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchLinear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchLinear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchLinear().setVisible(true);
            }
        });
    }
private void setBtnSize(int w,int h){
    for(int i = 0; i<9; ++i){
        arBt[i].setSize(w, h);
    }
}
private int checkBg(){
    int cnt = 0;
    for(int i = 0; i<9; ++i){
        if(arBt[i].getSize().width != btnNWidth || arBt[i].getSize().height != btnNHeight){
            return 1;
        }
    }
    return 0;
}

private void setBlack(){
    for(int i = 0; i<9; ++i){
        arBt[i].setSize(btnNWidth,btnNHeight);
    }
}

private void setWhite(){
    for(int i = 0; i<9; ++i){
        btL[i].setForeground(white);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KGradientPanel btn1;
    private com.k33ptoo.components.KGradientPanel btn2;
    private com.k33ptoo.components.KGradientPanel btn3;
    private com.k33ptoo.components.KGradientPanel btn4;
    private com.k33ptoo.components.KGradientPanel btn5;
    private com.k33ptoo.components.KGradientPanel btn6;
    private com.k33ptoo.components.KGradientPanel btn7;
    private com.k33ptoo.components.KGradientPanel btn8;
    private com.k33ptoo.components.KGradientPanel btn9;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton reset;
    private com.k33ptoo.components.KButton startSearch;
    // End of variables declaration//GEN-END:variables
}
